### ISSUE TITLE
【漏洞】长视频上传失败抛出异常

### ISSUE THREAD

**Issue by wshrzzz** [MoyuScript/bilibili-api#208]
**Python 版本：** 3.8.10

**模块版本：** 6.1.2

**运行环境：** wsl2 Ubuntu20.04LTS

**模块路径：** bilibili_api.video

**报错信息：**

```
异常 Server disconnected
```

**报错代码：**

```python
v1 = video.VideoUploaderPageObject(video_stream=open(input_video, "r+b"), title='test')
credential = Credential(sessdata=sessdata, bili_jct=bili_jct, buvid3=buvid3)
uploader = video.VideoUploader(cover=open(input_cover, "r+b"), cover_type='jpg', pages=[v1], config=upload_config, credential=credential)
result = await uploader.start()
```

---

通过 video.VideoUploader 上传超过1小时时长的视频会很快抛出异常，打印异常信息：Server disconnected
720p测试视频A 1:37:00时长，2.2G，平均目标码率 3M
720p测试视频B 1:00:00整，1.4G，平均目标码率 3M
A,B为平均目标码率相同的60fps视频
简单测试了将视频A,B分别截取至59:30长度可以正常完成上传
或将视频A平均目标码率压低到1.5M（低于B站标准上限码率1.7M），也能正常上传完整视频

（是我需要在哪里设置分段或二压之类的上传选项吗？）

**Comment by MoyuScript** [comment]
请提供报错代码调用栈

**Comment by wshrzzz** [comment]
> 请提供报错代码调用栈

ERROR:root:Server disconnected
Traceback (most recent call last):
  File "/mnt/c/test.py", line 58, in upload_video
    result = await uploader.start()
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/bilibili_api/video.py", line 1368, in start
    filename = await self.__upload_video(page)
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/bilibili_api/video.py", line 1440, in __upload_video
    upload_info = await self.__get_upload_info(page)
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/bilibili_api/video.py", line 1637, in __get_upload_info
    async with self.__session.get(
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 890, in start
    message, payload = await self._protocol.read()  # type: ignore
  File "/mnt/c/wsl_env/lib/python3.8/site-packages/aiohttp/streams.py", line 604, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

**Comment by MoyuScript** [comment]
提示是被关闭连接，之后这个接口也要大改一次，请耐心等待修改。

**Comment by MoyuScript** [comment]
应该是长视频上传的分块多了，偶尔会出现错误但是没考虑到这种情况。

7.0.0 更新了 API，也对这种情况进行了处理，可以看看 https://www.moyu.moe/bilibili-api/#/examples/video_uploader

**Comment by wshrzzz** [comment]
> 应该是长视频上传的分块多了，偶尔会出现错误但是没考虑到这种情况。
> 
> 7.0.0 更新了 API，也对这种情况进行了处理，可以看看 https://www.moyu.moe/bilibili-api/#/examples/video_uploader

7.0.0 requirement.txt 没加 rsa，video_uploader.py 332行 参数类型 list[...] 报错

**Comment by MoyuScript** [comment]
看看 7.0.1

**Comment by wshrzzz** [comment]
run了几天似乎是没碰到问题了，感谢
