### ISSUE TITLE
无法打包exe

### ISSUE THREAD

**Issue by Shapaper** [MoyuScript/bilibili-api#219]
打包后错误提示：
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "ea.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\bilibili_api\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\bilibili_api\video.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\bilibili_api\user.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\bilibili_api\common.py", line 15, in <module>
  File "site-packages\bilibili_api\utils.py", line 48, in get_api
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\lenovo\\AppData\\Local\\Temp\\_MEI233002\\bilibili_api\\data/api.json'
[24588] Failed to execute script main

**Comment by Shapaper** [comment]
打包参数：pyinstaller --hidden-import=pkg_resources -F I:\Python_program\up主桌面小挂件\main.py -p I:\Python_program\up主桌面小挂件\ea.py

**Comment by MoyuScript** [comment]
需要同时打包 data/ 里面的数据

**Comment by Shapaper** [comment]
date?在哪里

**Comment by Shapaper** [comment]
如何操作？怎样更改打包命令

**Comment by Shapaper** [comment]
变了：
Traceback (most recent call last):
  File "main.py", line 170, in <module>
    face_url = ea.face_url()
  File "ea.py", line 79, in face_url
    return sync(u.get_user_info())["face"]
  File "bilibili_api\utils\sync.py", line 16, in sync
  File "asyncio\base_events.py", line 584, in run_until_complete
  File "bilibili_api\user.py", line 117, in get_user_info
TypeError: 'NoneType' object is not subscriptable
[21352] Failed to execute script 'main' due to unhandled exception!

**Comment by MoyuScript** [comment]
这个问题需要你自己解决了，我不了解 pyinstaller
