### ISSUE TITLE
【漏洞】这个库的接口不方便在 sync 环境中使用

### ISSUE THREAD

**Issue by cosven** [MoyuScript/bilibili-api#245]
**Python 版本：** 3.9.7

**模块版本：** /9.0.0/

**运行环境：** Linux

**模块路径：** bilibili_api.xxxx

**报错信息：**

```
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 438, in result                                                    
    return self.__get_result()                                                                                                  
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result                                              
    raise self._exception                                                                                                       
  File "/home/cosven/coding/FeelUOwn/feeluown/utils/sync.py", line 328, in main_wrap                                            
    result = await self.awaitable(*args, **kwargs)                                                                              
  File "/home/cosven/coding/FeelUOwn/.venv/lib/python3.9/site-packages/bilibili_api/video.py", line 253, in get_download_url    
    return await request("GET", url, params=params, credential=self.credential)                                                 
  File "/home/cosven/coding/FeelUOwn/.venv/lib/python3.9/site-packages/bilibili_api/utils/network.py", line 111, in request     
    async with session.request(**config) as resp:                                                                               
  File "/home/cosven/coding/FeelUOwn/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 1117, in __aenter__             
    self._resp = await self._coro                                                                                               
  File "/home/cosven/coding/FeelUOwn/.venv/lib/python3.9/site-packages/aiohttp/client.py", line 429, in _request                
    handle = tm.start()                                                                                                         
  File "/home/cosven/coding/FeelUOwn/.venv/lib/python3.9/site-packages/aiohttp/helpers.py", line 586, in start                  
    return self._loop.call_at(when, self.__call__)                                                                              
  File "/usr/lib/python3.9/asyncio/base_events.py", line 725, in call_at                                                        
    self._check_closed()                                                                                                        
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed                                                  
    raise RuntimeError('Event loop is closed')                                                                                  
RuntimeError: Event loop is closed
```

**报错代码：**

```python
In [11]: import threading
    ...: from bilibili_api.utils.sync import sync
    ...: from bilibili_api.video import Video
    ...: 
    ...: def task():
    ...:     v = Video("BV18s411W7by")
    ...:     sync(v.get_download_url())
    ...: 
    ...: t = threading.Thread(target=task)
    ...: t.start()
    ...: t.join()
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-11-bc2d1e0989ef>", line 7, in task
  File "/home/cosven/coding/FeelUOwn/.venv/lib/python3.9/site-packages/bilibili_api/utils/sync.py", line 15, in sync
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3'.
/usr/lib/python3.9/threading.py:975: RuntimeWarning: coroutine 'Video.get_download_url' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

---

在 sync 环境下使用这个库，遇到了两个问题
1. utils 里面的 sync 方法在很多情况下都不能正常的工作，不是很鲁棒。上面是一个例子。我查了一些资料，目前看起来 https://github.com/django/asgiref/blob/35919960cd/asgiref/sync.py 这个实现相对比较鲁棒。
2. 还有一个问题，network 模块里面的 session 是一个全局的，多线程其实不能共用着一个 session。查了一些资料，感觉可以做成 thread local 的。

**Comment by MoyuScript** [comment]
哥，学一下异步吧

**Comment by cosven** [comment]
我这边是个老项目，短时间迁移不了，只能在 sync code 里面调用 async code。

**Comment by cosven** [comment]
我看项目的 README 里面提了这个 sync 方法，所以提一个 issue，看看作者有没有兴趣解决一下 ～

**Comment by MoyuScript** [comment]
有个简单的办法可以解决：
```python
from bilibili_api import video, sync
from threading import Thread
import asyncio

async def main():
    v = video.Video('BV1s34y1Q7Kq')
    print(await v.get_info())

def thread():
    try:
        asyncio.get_event_loop()
    except:
        asyncio.set_event_loop(asyncio.new_event_loop())
    sync(main())

th = Thread(target=thread)

th.start()
th.join()

```

**Comment by MoyuScript** [comment]
试试 9.0.2 ，应该是可以用了

**Comment by cosven** [comment]
感谢调研，我现在是这样处理的 ~
https://github.com/feeluown/feeluown-bilibili/blob/782e91946a31e9a755b83b783c87163c8871f1bb/fuo_bilibili.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L39-L74

**Comment by lb-chc** [comment]
> 哥，学一下异步吧

问一下，如果我不管同步异步直接用的话是不是也会没法运行......就，我刚学了py的hello world......

**Comment by MoyuScript** [comment]
> > 哥，学一下异步吧
> 
> 问一下，如果我不管同步异步直接用的话是不是也会没法运行......就，我刚学了py的hello world......

用 bilibili_api.sync() 包裹一下异步函数就可以当同步用了

**Comment by ClintYJQ** [comment]
使用sync包裹的时候报错：
Traceback (most recent call last):
  File "C:\Python39\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python39\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python39\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python39\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python39\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python39\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python39\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Python39\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python39\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Python39\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python39\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\DATA\GitProject\flask-vue-crud-master\server\app.py", line 26, in get_bv
    info = executor.submit(demoBilibili_api.getVideoInfo(bv))
  File "D:\DATA\GitProject\flask-vue-crud-master\server\bilibili\demoBilibili_api.py", line 11, in getVideoInfo
    info = sync(v.get_info())
  File "C:\Python39\Lib\site-packages\bilibili_api\utils\sync.py", line 15, in sync
    loop = asyncio.get_event_loop()
  File "C:\Python39\Lib\asyncio\events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-2'.

应用场景是在flask服务端调用了get_info函数
异步还不是很明白 不知道是库的问题还是我应用的问题，提交一下，看看能不能有点思路；

**Comment by MoyuScript** [comment]
> 使用sync包裹的时候报错： Traceback (most recent call last): File "C:\Python39\Lib\site-packages\flask\app.py", line 2464, in **call** return self.wsgi_app(environ, start_response) File "C:\Python39\Lib\site-packages\flask\app.py", line 2450, in wsgi_app response = self.handle_exception(e) File "C:\Python39\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "C:\Python39\Lib\site-packages\flask\app.py", line 1867, in handle_exception reraise(exc_type, exc_value, tb) File "C:\Python39\Lib\site-packages\flask_compat.py", line 39, in reraise raise value File "C:\Python39\Lib\site-packages\flask\app.py", line 2447, in wsgi_app response = self.full_dispatch_request() File "C:\Python39\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "C:\Python39\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function return cors_after_request(app.make_response(f(*args, **kwargs))) File "C:\Python39\Lib\site-packages\flask\app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) File "C:\Python39\Lib\site-packages\flask_compat.py", line 39, in reraise raise value File "C:\Python39\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "C:\Python39\Lib\site-packages\flask\app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "D:\DATA\GitProject\flask-vue-crud-master\server\app.py", line 26, in get_bv info = executor.submit(demoBilibili_api.getVideoInfo(bv)) File "D:\DATA\GitProject\flask-vue-crud-master\server\bilibili\demoBilibili_api.py", line 11, in getVideoInfo info = sync(v.get_info()) File "C:\Python39\Lib\site-packages\bilibili_api\utils\sync.py", line 15, in sync loop = asyncio.get_event_loop() File "C:\Python39\Lib\asyncio\events.py", line 642, in get_event_loop raise RuntimeError('There is no current event loop in thread %r.' RuntimeError: There is no current event loop in thread 'Thread-2'.
> 
> 应用场景是在flask服务端调用了get_info函数 异步还不是很明白 不知道是库的问题还是我应用的问题，提交一下，看看能不能有点思路；

请单独使用模板提交 issue
