### ISSUE TITLE
【提问】获取文章内容失败

### ISSUE THREAD

**Issue by falcomzwei** [MoyuScript/bilibili-api#269]
```
Traceback (most recent call last):
    await ar.fetch_content()
  File "C:\python310\lib\site-packages\bilibili_api\article.py", line 366, in fetch_content
    self.__children = parse(document.find('div'))
  File "C:\python310\lib\site-packages\bilibili_api\article.py", line 167, in parse
    node.children = parse(e)
  File "C:\python310\lib\site-packages\bilibili_api\article.py", line 215, in parse
    node.color = ARTICLE_COLOR_MAP[color_text]
KeyError: 'default'
```

报的这个错

**Comment by MoyuScript** [comment]
请使用漏洞 issue 模板
